(defsystem "project" :components ((:file "player") 
                                  (:file "array-utils")
                                  (:file "card")
                                  (:file "deck")
                                  (:file "main")))